### ISSUE TITLE
Documents Scanned to PDF Appear Blank in Seer

### ISSUE THREAD

**Issue by kwehner** [ccseer/Seer#114]
When I scan a document to a .pdf file using the Epson Scan utility, they appear blank when viewed in Seer. The documents display correctly when opened in Adobe Acrobat. I'm running Windows Pro version 10.0.14393 and Seer version 1.6.0. See attached sample .pdf file. 
[img047.pdf](https://github.com/ccseer/Seer/files/1249325/img047.pdf)

**Comment by ccseer** [comment]
Thank you for your report.
 
I am planning to replace the PDF module with a new one in next version.

**Comment by ccseer** [comment]
To fix all these bugs once for all

**Comment by ccseer** [comment]
Hi
Please email me if you want to roll back to old version

**Comment by kwehner** [comment]
I don’t mind waiting until you can fix the pdf issue. Thanks!

Kevin

**Comment by openslot** [comment]
I'm also having issues with this as almost all of my PDFs are scanned documents. For whatever it's worth, I don't use the Epson Scan Utility to scan documents; instead, I use a ScanSnap scanner. I'm inclined to believe therefore it's not an issue related to how Epson scans its documents. Please fix this at your earliest convenience. I love Seer and use it for work but this bug is breaking the software for me. Thank you :-)

**Comment by ccseer** [comment]
Hi~

I am working very hard on the new PDF module. And it's really amazing.

Please email me for old version download link.


Avnish Mangal <notifications@github.com>于2017年9月19日周二 下午10:31写道：

**Comment by ccseer** [comment]
All bugs of PDF module has been fixed. New version will be released in a month

**Comment by ccseer** [comment]
fixed in 1.7.0
