### ISSUE TITLE
Uninstall file is missing

### ISSUE THREAD

**Issue by JBinAussie** [ccseer/Seer#216]
I just installed v 2.2.0 from the download link on http://1218.io/ to evaluate it, which I couldn't do properly as it appears I have to pay for a single machine license to be able to get to the settings options?  

So I tried to uninstall it and found that I can't, the uninstall file is missing!?  I've searched in the install directory and there is no uninst.exe to be found?

How do I uninstall it without that file?

**Comment by ccseer** [comment]
Seer has a 3-day free trail. After that, it stops working.
If you are concerning about licensing, Seer also has a uwp version:
https://www.microsoft.com/store/apps/9PGVFJBVBZWX
However, due to the Windows Store's policy, some features are disabled.

And if you still want to uninstall it, you can try to install it again in
the same folder.

Thank you~

**Comment by JBinAussie** [comment]
Thanks for the reply, I've tried reinstalling it twice, but there is still no uninst.exe file. When I try to uninstall it I get an error saying the uninstall file can't be found? I've even tried logging in as an administrator and installing it to see if the usual user account was messing things up.

Any other ideas?

Thanks

**Comment by ccseer** [comment]
Seer use three paths.
1. %TEMP%/Seer
2. %APPDATA%/local
3. installation folder

rededit
HKEY_CURRENT_USER\Software\Corey
