### ISSUE TITLE
[Feature Request] Please, do not Lock File & Folder after Audio Playback 

### ISSUE THREAD

**Issue by daslicht** [ccseer/Seer#272]
Hi,
please release a file once it has been played fully so that we can move it without closing the Seer Popup windows after each play.

**Comment by ccseer** [comment]
Some file formats cannot be fully loaded, because

   - the size is too large to load into the memory, e.g.: video
   - it would be faster to parse the file separately, e.g.: text, pdf

Meanwhile, it would cause some errors when you take actions(Separate, Open
with default application and so on) from the Control panel in the bottom.


btw, the Folder type can be deleted if the data are fully loaded.

**Comment by ccseer** [comment]
The main point here is that  the time Seer can only tell the file should be released is when the preview window is closed.
Otherwise, there is no way to determine that file is not used by Seer any more.

**Comment by daslicht** [comment]
Programartically shoudl this be possibvle since other Software(qucklook, resonic...) has that behavior .
Maybe just release teh file once the playback finished ?

**Comment by ccseer** [comment]
What version are you using now?

**Comment by daslicht** [comment]
0.8.1

**Comment by ccseer** [comment]
Sorry.

The free version is not updating any more.
The latest version is 2.6.1 now.
http://1218.io/seer/release-note.html

**Comment by daslicht** [comment]
No need to be sorry, is there a demo version of the  paid version available, that I can try if it suits my needs.

**Comment by ccseer** [comment]
It locks the file as well.
Uninstall free version, and install 2.6.1, it has a 3 days free trial
