### ISSUE TITLE
Unable to Preview .CR2 files

### ISSUE THREAD

**Issue by neuro-81** [ccseer/Seer#273]
Hello! 
Seer will not preview many of my CR2 files. 
Some CR2 files it will preview while the vast majority it will not. 

Seer does read .arw files however, loading is very very slow. 

Thanks, 
Michael

**Comment by ccseer** [comment]
cr2 can be read by the plugin imagemagick
but you need add the extension yourself

![image](https://user-images.githubusercontent.com/15963166/101110707-898e9200-3614-11eb-8f2a-572fd011b10c.png)

**Comment by neuro-81** [comment]
I don't know what that means. I have all the Adobe Software on my system and they can read all canon raw files, however, this doesn't make sense and I don't see a folder to place an extension into.

**Comment by neuro-81** [comment]
Thank you! 
I understand how this works now. 

Does it not conflict with what is under type/image/cr2 ?

**Comment by ccseer** [comment]
Seer checks extensions from plugins first.
So the extensions you write in plugin, the internal supported file type
will be ignored.

**Comment by neuro-81** [comment]
Got it! 
Thank you! 
Any way to speed up the ImageMagic PlugIn?
Over 10 seconds to generate a preview on a powerful system.

**Comment by ccseer** [comment]
As you can see, Seer run plugin with the command to convert a unknown file to internal supported type, then Seer loads the converted file.

You can modify the command to customize the output.
![image](https://user-images.githubusercontent.com/15963166/101118096-661f1380-3623-11eb-8902-a192d8be0b42.png)


for example, adding " -resize 50%" maybe could reduce the converting time.

One thing is that the file would only be converted once if the file content is not changed so that the second time you preview a converted file would be faster. 
And if you changed the command, you need to remove converted files in temp folder.
![image](https://user-images.githubusercontent.com/15963166/101118356-da59b700-3623-11eb-9519-ccc95dda4509.png)

**Comment by ccseer** [comment]
in your case, it would be look like this
![image](https://user-images.githubusercontent.com/15963166/101118560-4b00d380-3624-11eb-9ff3-bf734eade0e9.png)

**Comment by neuro-81** [comment]
You you be able to assist in where I would add the following: 

for example, adding " -resize 50%" maybe could reduce the converting time.

**Comment by neuro-81** [comment]
Perfect! Thank you!

**Comment by ccseer** [comment]
Please remove the plugin. 
Seer supports raw image internally after 2.8.3.

**Comment by neuro-81** [comment]
Confirmed - DNG and CR2 preview is working.

**Comment by ccseer** [comment]
oh, I just released 2.8.4

**Comment by neuro-81** [comment]
I did update to 2.8.4
