### ISSUE TITLE
How do I access settings after hiding the icon in the Microsoft Store version?

### ISSUE THREAD

**Issue by ferrazpedro** [ccseer/Seer#286]
Well, the question is in the title

**Comment by ccseer** [comment]
Kill the process.
Start the software again, it will display the icon in the taskbar for 5 s

**Comment by ccseer** [comment]
it will be 8s since Seer-2.7.0

**Comment by highend** [comment]
Hello.

Sorry but if I want to hide a tray icon, I want to hide it and not show up for <whatever> seconds instead and the necessity to quit the application first is everything but not user friendly... 

Can't you add another entry in:
Settings - Keyboard

Like "Trigger Settings Key(s)"

so that we can bind a keyboard shortcut to show the setting window?

Thanks

**Comment by ccseer** [comment]
It is difficult  to remember a shortcut which is not frequently used.

**Comment by highend** [comment]
That depends on the shortcut that the user sets^^ and with that argument you could remove 50% of all other shortcuts as well or do you really think that e.g. F4 is a commonly used shortcut for "Separate"?

**Comment by ccseer** [comment]
Good point.
I will think about it.

**Comment by ccseer** [comment]
I think I will use shortcut to restore icon in Seer-3.0.0 .

**Comment by highend** [comment]
Thx!

**Comment by ccseer** [comment]
added `Ctrl+,` in Seer-4.0.0
