### ISSUE TITLE
Doesn't work with the ''Files'' file manager.

### ISSUE THREAD

**Issue by rp1231** [ccseer/Seer#349]
It doesn't work with the "'Files'' file manager on windows 11.

Also is there a difference between the seer pro available on the store and the normal seer installer?
Which one is preferred?

Thanks

**Comment by ccseer** [comment]
1. Windows Store manages to control the license, updates and trail. 
2. Windows Store allows you to install on 10 PCs based on your MS account, if it's win32 version, you need to email me everytime you have a new PC.
3. Due to some Store policies, a few feature of Seer Pro is disabled, like triggering in a "Open/Save file dialog". 
4. Win32 is more managable, if you have some bug, I can help you to solve it by replacing files while Windows Store does not allow  user to modify files.

**Comment by rp1231** [comment]
Thanks
