### ISSUE TITLE
Seer is no longer functioning.

### ISSUE THREAD

**Issue by mrdfrost** [ccseer/Seer#59]
No idea why. tried to get the log
https://www.dropbox.com/s/bocckd8sp3rtxlw/Screenshot%202016-10-13%2006.57.33.png?dl=0

**Comment by mrdfrost** [comment]
However it does show seer is running.

**Comment by danguilherme** [comment]
Same here... I had the latest version (don't remember the version number, but accepted all software update requests).

Had to install [v0.8.0](https://sourceforge.net/projects/ccseer/) again and now it works again. Will not update until this issue is resolved :)

Is it paid now? Well... then I'm saving this v0.8 copy forever.
![Seer Update](https://cloud.githubusercontent.com/assets/1488378/19351749/51e935ba-9133-11e6-9743-3f70248fb2b5.png)

**Comment by ccseer** [comment]
http://1218.io/app/last-relnotes.html

thank you for using Seer.

**Comment by ccseer** [comment]
@mrdfrost  you can download  v0.8.0. It's free.

http://1218.io/order/order.html
